### ISSUE TITLE
Gitlab ID to manage the AppImage via "AM" package manager

### ISSUE THREAD

**Issue by ivan-hc** [dr460nf1r3/firedragon-browser#115]
Hi @dr460nf1r3 , do you remember me? I'm the one that proposed time ago an AppImage for Firedragon.

I'm still maintaining the unofficial build at https://github.com/ivan-hc/Firedragon-appimage but I was not aware that you released an official AppImage. I'm now ready to archive my repo.

Since the AppImage is hosted on Gitlab, I need your repo ID to create an installation script for "AM" package manager, at https://github.com/ivan-hc/AM, Gitlab APIs are a lot different from the ones of github.

For example, these are three apps managed by "AM" and that are hosted on gitlab
```
version=$(curl -Ls https://gitlab.com/api/v4/projects/37138263/releases/ | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i .appimage | head -1 | sed 's#/file/#/raw/#')
version=$(curl -Ls https://gitlab.com/api/v4/projects/18817634/releases/ | grep -Eo 'v[0-9].[0-9].[0-9]+' | head -1)
version=$(curl -Ls https://gitlab.com/api/v4/projects/44426042/releases/ | grep -Eo 'v[0-9].[0-9].[0-9]+' | head -1)
```
I need the ID number in the URL
```
https://gitlab.com/api/v4/projects/ID/releases/
```
Can you provide it please?

**Comment by ivan-hc** [comment]
OK, I've solved by myself

- https://github.com/ivan-hc/AM/commit/58f92f4eabb07071442aae7338cb0f7e584a9e6e
- https://github.com/ivan-hc/AM/commit/a19aad2365326d90fa2f331b3ec16cac8a9bd2d9
- https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/1a568e1f80f7fec6a9acf9ad83dd05aad6ff9fd5

thanks, I go archive my repo.

See you next!

**Comment by dr460nf1r3** [comment]
Hey, of course I remember you :)
Thanks for maintaining the unofficial AppImage till this day. I appreciate it!

Now that we have a build system and binary tarballs, it was possible to easily build AppImages directly via the build system itself in an automated way.

**Comment by Samueru-sama** [comment]
> Hey, of course I remember you :) Thanks for maintaining the unofficial AppImage till this day. I appreciate it!
> 
> Now that we have a build system and binary tarballs, it was possible to easily build AppImages directly via the build system itself in an automated way.

Hey thanks for providing the appimage officially, however there is a small issue with it that the appimage Ivan was making didn't have. 

The runtime being used is the old runtime that depends on libfuse2 which is no longer shipped on newer distros: https://gitlab.com/garuda-linux/firedragon/builder/-/blob/main/assets/appimage-x86_64.mk?ref_type=heads#L23

The fix is as simple as changing that URL for this runtime instead: https://github.com/AppImage/type2-runtime/releases

Where all the continuous releases are the static runtime which has no libfuse dependency, it is the runtime that was being used on Ivan's AppImage as well as other appimages like Cemu, Zen Browser, PSCX2, etc

Also note that if you switch to this [appimagetool](https://github.com/AppImage/appimagetool) you don't have to manually download the runtime since it will do it automatically, as well as use zstd compression which will result in a slightly smaller appimage that also starts up faster.
