### ISSUE TITLE
How to build it for NixOs

### ISSUE THREAD

**Issue by tofooNinja** [dr460nf1r3/firedragon-browser#35]
Hey,
I'm not sure if this is the right place to get support but I'm not sure where else to ask.
I'm running NixOs and would like to use Firedragon but I'm not sure how to build it locally. Can somebody pleas help me out?

**Comment by dr460nf1r3** [comment]
Hey :) Currently, there aren't any manual build instructions as these would change more or less frequently due to the patches which need to get applied to the source. The [Archlinux PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon) on AUR however provides instructions that could be converted to manual instructions:
1. Clone the sources of the `source` array
2. Then follow the `prepare` function (which is more or less a bash script), starting by running the [sed commands](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n69) on the patches in question
3. Run [this script](https://github.com/dr460nf1r3/firedragon-design/blob/master/rebrand.sh) on the cloned patches dirs, I stopped maintaining them pre-patched some time ago to save time spent maintaining
4. Create the [mozconfig file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n82) as outlined in the PKGBUILD, replacing the variables of course. The later [added options](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n160) also need to be added to the same file.
5. Apply [all the of the patches to the source](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n172)
6. Move the [mozconfig file to the right location](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n267)
7. Follow the `build` and `package` functions, like the `prepare` functions these are pretty much bash scripts. The package function installs to the `makepkg` specific `$pkgdir`, this could be replaced with `/` if an installation to the system is desired. 

I know this is some work to be done and I didn't plan to maintain additional ways to compile this until now. If someone else decides to package the browser for other distributions I'd be glad. It is also important to have respective OS packages of the in the `depends` and `makedepends` arrays mentioned applications installed (pretty much runtime vs build dependencies). I hope this provides some useful directions to follow, I'm of course available for further questions :)

**Comment by MrSchnitzel** [comment]
Thanks for the super fast response!
I'll try my best to follow the instructions and see how far I make it :)

**Comment by dr460nf1r3** [comment]
I'm actually in the progress of packaging FireDragon for NixOS!

**Comment by dr460nf1r3** [comment]
Case closed, it is available pre-built via Chaotic Nyx! :) https://github.com/chaotic-aur/nyx

**Comment by tofooNinja** [comment]
Thanks; nice work :tada:
