### ISSUE TITLE
brave search

### ISSUE THREAD

**Issue by Martinligabue** [dr460nf1r3/firedragon-browser#67]
I think another good and private search engine to add to the default list might be search.brave.com

**Comment by Technetium1** [comment]
> Web search, Goggles, Extra alternate snippets for AI, **_Rights to use data for AI inference_**, News, Videos, Images
(https://brave.com/search/api/)

Signing off rights to your queries to be used for AI inference doesn't feel very private at all. Especially when it's not directly mentioned in the same words in their ToS as far as I can find. Maybe as [their Leo AI product](https://brave.com/leo-roadmap/) rolls out more, they will update policy to say more about this data they harvest?

**Comment by dr460nf1r3** [comment]
Interesting. Didn't know about that yet :eyes: How did you find it @Technetium1 ?

**Comment by Martinligabue** [comment]
he is referring to the free service "Data for AI" he linked, that will use the data for those services, (and since that's just the ad and not the actual tos it's not really clear what it's about), that's not the search engine.

According to Wikipedia, and the sources provided as reference for that sentences https://en.wikipedia.org/wiki/Brave_Search

> However, the user can allow the Brave browser to anonymously check [Google](https://en.wikipedia.org/wiki/Google_search) for the same query.[[](https://en.wikipedia.org/wiki/Brave_Search#cite_note-4)


so that's opt-in, and

> Brave Search implements some level of [data collection](https://en.wikipedia.org/wiki/Data_collection) only when users opt in through the Web Discovery Project (WDP).

also opt-in.

The only actual concern, afaik, might be

> Brave Search is not yet open-source like Brave Browser

**Comment by Technetium1** [comment]
This AI functionality is on *by default*', how then is it **opt-in**? To me, opt-in that means functionality is off unless I decide I specifically and intentionally want to enable. I am admittedly in the USA, so maybe the rest of the world doesn't have this toggled? 😕 

I would like to note a technicality of LLM functionality, especially in terms of their policy. Inference is the process of taking an input (user data in this case), and handing it to an LLM, in order to get probabilistic outcomes of the next most common tokens. At the moment they decide to summarize (_when you decide to search_), **inference is happening on your data**.

[This notice is linked in that section of settings](https://search.brave.com/help/ai), which is thereby implicating their AI engine Leo.

Settings page: https://search.brave.com/settings
![image](https://github.com/dr460nf1r3/firedragon-browser/assets/9877150/5d94863e-e1b2-4a12-8070-0d3ce2ac5cc0)

---

I'm not concerned that they're not open source, though it would be much cooler if they were. I'm displeased that their privacy policy feels so lacking in terms of the LLM functionality which is enabled by default.

**Comment by Martinligabue** [comment]
I see, then I agree their tos are not really clear, thanks

**Comment by dr460nf1r3** [comment]
I wonder if there is a way to disable those by default, ug. by using specific URL parameters 👀

**Comment by Technetium1** [comment]
It's cookie based unfortunately:
`summarizer=0; Path=/; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Secure; SameSite=Lax`

**Comment by dr460nf1r3** [comment]
I'm inclined to not add it then.
